config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }
  root 'home#top'
  resources :users,only: [:show,:index,:edit,:update]
  get "user/show_follow/:id" => "users#show_follow", as: "user_show_follow"
  get "user/show_follower/:id" => "users#show_follower", as: "user_show_follower"
  get "search" => "searches#search"
  resources :relationships, only: [:create, :destroy]
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  
  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resource :book_comments, only: [:create, :destroy]
  end
  get 'home/about'
end

app/models/favorite.rb
class Favorite < ApplicationRecord

 belongs_to :user
 belongs_to :book
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
		user = current_user
        @book = Book.find(params[:book_id])
        favorite = Favorite.new(user_id: user.id, book_id: @book.id)
        favorite.save
	end

	def destroy
		user = current_user
	    @book = Book.find(params[:book_id])
	    favorite = Favorite.find_by(user_id: user.id, book_id: @book.id)
	    favorite.destroy
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<div id = "favorite_buttons_<%= book.id %>">
	<% if user_signed_in? %>
	<% if book.favorited_by?(current_user) %>
	<li>
		<%= link_to book_favorites_path(book), method: :delete, remote: true do %>
		<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
		<%= book.favorites.count %>
		<% end %>
	</li>
	<% else %>
	<li>
		<%= link_to book_favorites_path(book), method: :post, remote: true do %>
		<i class="fa fa-heart" aria-hidden="true"></i>
		<%= book.favorites.count %>
		<% end %>
	</li>
	<% end %>
	<% end %>
</div>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorite', locals: { book: @book})%>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorite', locals: { book: @book })%>");