config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }
  root 'home#top'
  resources :users,only: [:show,:index,:edit,:update]
  get "user/show_follow/:id" => "users#show_follow", as: "user_show_follow"
  get "user/show_follower/:id" => "users#show_follower", as: "user_show_follower"
  get "search" => "searches#search"
  resources :relationships, only: [:create, :destroy]
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  
  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resource :book_comments, only: [:create, :destroy]
  end
  get 'home/about'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  # フォロー関連(relationships)紐付け
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
# フォロー関連終わり
# 検索関連
def self.search(search,word)
      if search == "forward_match"
        @user = User.where("name LIKE?","#{word}%")
      elsif search == "backward_match"
        @user = User.where("name LIKE?","%#{word}")
      elsif search == "perfect_match"
        @user = User.where("#{word}")
      elsif search == "partial_match"
        @user = User.where("name LIKE?","%#{word}%")
      else
        @user = User.all
      end
end
# 検索関連終わり


  attachment :profile_image, destroy: false

  # 住所関連 Jp＿prefectureをuserモデルに読み込み
  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
  JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
  self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  def address
  self.prefecture_code + self.city + self.street
  end
# 住所関連終わり
# map関連
  geocoded_by :address
  after_validation :geocode, if: :name_changed?
#map関連終わり

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

   # POST /resource
   def create
    super
    ThanksMailer.complete_mail(@user).deliver_now
   end

   # GET /resource/edit
   # def edit
   #  super
   # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update]

  def show
    @user = User.find(params[:id])
    @currentUserEntry=UserRoom.where(user_id: current_user.id)
    @userEntry=UserRoom.where(user_id: @user.id)
    @books = @user.books
    @book = Book.new
    # DM関連
    unless @user.id == current_user.id
      @currentUserEntry.each do |cuser|
        @userEntry.each do |user|
          if cuser.room_id == user.room_id then
            @isRoom = true
            @roomId = cuser.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = UserRoom.new
      end
    end
    # DM関連終わり
  end

  def index
    @users = User.all
    @book = Book.new
  end
  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(current_user.id), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def show_follow
    @user = User.find(params[:id])
  end

  def show_follower
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :postal_code, :prefecture_code, :city, :street)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
	<tr>
		<th>follows</th>
		<th><%= link_to user.followings.count, user_show_follow_path(user) %></th>
	</tr>
	<tr>
		<th>followers</th>
		<th><%= link_to user.followers.count,  user_show_follower_path(user) %></th>
	</tr>
</table>

<div class="row">
	<!-- DMボタン -->
	<% unless @user.id == current_user.id %>
	<% if (current_user.followed_by? @user) && (@user.followed_by? current_user)  %>
	<% if @isRoom == true %>
	<p class="user-show-room"><a href="/rooms/<%= @roomId %>" class="btn btn-primary btn-lg">チャットへ</a>
		<% else %>
		<%= form_for @room do |f| %>
		<%= fields_for @entry do |e| %>
		<%= e.hidden_field :user_id, value: @user.id %>
		<% end %>
		<%= f.submit "チャットを始める", class:"btn btn-primary btn-lg user-show-chat"%>
		<% end %>
		<% end %>
		<% end %>
		<% end %>
		<!-- DMボタン終わり -->
	<% if user == current_user %>
	<%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	<% end %>
	<div class= "col-xs-12">
		<%= render "relationships/follow_button", user: user %>
	</div>
</div>

app/views/users/edit.html.erb
<div class="flash"><%= flash[:notice] %></div>
<h2>User info</h2>

<%= form_for(@user) do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>error
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/index.html.erb
<div class = "container">
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Users</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
			        <th>name</th>
			        <th colspan="3"></th>
		        </tr>
	        </thead>

	    <tbody>
		    <% @users.each do |user| %>
		    <tr>
		    	<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
		    	<td><%= user.name %></td>
		    	<td>フォロー数<%= user.followings.count %></td>
		    	<td>フォロワー数<%= user.followers.count %></td>
		    	<td><%= render "relationships/follow_button", user: user %></td>
			    <td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
		    </tr>
		    <% end %>
		</tbody>
	</table>
	<!--users一覧 -->
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book.user), class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>
<!-- map表示 -->
<div class = "row">
	<div class = "col-xs-12">
		<% if @user == current_user %>
		<h2>Your MAP</h2>
		<div id='map'></div>

<style>
#map {
  height: 400px;
  width: 100%;
}
</style>

<script>
let map

function initMap(){
	var test ={lat: <%= @user.latitude %>, lng: <%= @user.longitude %>};
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
  	zoom: 15,
    center: test,
  });

  marker = new google.maps.Marker({
    position:test,
    map: map
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>
<% end %>
	    </div>
	</div>
</div>

app/views/users/show_follow.html.erb
<div class = "container">
	<div class = "low">
		<h1>follow一覧</h1>
		<% if @user.followings.count == 0 %>
		<p>フォローしていません</p>
		<% else %>
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
			        <th>name</th>
			        <th colspan="3"></th>
		        </tr>
	        </thead>
	        <tbody>
	        	<!-- フォロー一覧 -->
	        	<% @user.followings.each do |user| %>
	        	<tr>
	        		<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
		    	    <td><%= user.name %></td>
		    	    <td>フォロー数<%= user.followings.count %></td>
		    	    <td>フォロワー数<%= user.followers.count %></td>
			        <td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
		        </tr>
		        <% end %>
		    </tbody>
	    </table>
	    <% end %>
    </div>
</div>

app/views/users/show_follower.html.erb
<div class = "container">
	<div class = "low">
		<h1>follower一覧</h1>
		<% if @user.followers.count == 0 %>
		<p>フォロワーはいません</p>
		<% else %>
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
			        <th>name</th>
			        <th colspan="3"></th>
		        </tr>
	        </thead>
	        <tbody>
	        	<!-- フォロワー　一覧 -->
	        	<% @user.followers.each do |user| %>
	        	<tr>
	        		<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
		    	    <td><%= user.name %></td>
		    	    <td>フォロー数<%= user.followings.count %></td>
		    	    <td>フォロワー数<%= user.followers.count %></td>
			        <td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
		        </tr>
		        <% end %>
		    </tbody>
	    </table>
	    <% end %>
    </div>
</div>